apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.8
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/config.yaml
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          ports:
            - containerPort: 3100
              protocol: TCP
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/config.yaml
              subPath: config.yaml
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-cm
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data
