apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: alloy
          image: grafana/alloy:v1.7.5
          imagePullPolicy: IfNotPresent
          args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - /etc/alloy/config.alloy
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          ports:
            - containerPort: 12345
              protocol: TCP
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy/config.alloy
              subPath: config.alloy
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-cm
