{
 "title": "Keycloak",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "app", "query": "keycloak" }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"$app\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$app\"}*1000"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://auth.pausegarra.es/health/live\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage Max Peak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container) (container_memory_max_usage_bytes{job=\"cadvisor\", namespace=\"main\", container=\"$app\", image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$app\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$app\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$app\"}[2m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\", job=\"$app\"}[2m])) / sum(rate(http_server_requests_seconds_count{status!~\"5..\", job=\"$app\"}[2m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{status!~\"5..\", job=\"$app\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"$app\", status=~\"5..\"}[1m])",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"$app\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$app\", area=\"nonheap\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$app\"})",
     "legendFormat": "used"
    },
    {
     "expr": "max by (container) (container_memory_usage_bytes{job=\"cadvisor\", namespace=\"main\", container=\"$app\", image!=\"\"})",
     "legendFormat": "container"
    },
    {
     "expr": "max by (container) (container_spec_memory_limit_bytes{job=\"cadvisor\", namespace=\"main\", container=\"$app\", image!=\"\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\", namespace=\"main\", container=\"$app\", image!=\"\"}[1m])) by (container) *100",
     "legendFormat": "container"
    },
    {
     "expr": "process_cpu_usage{job=\"$app\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (container) (rate(container_cpu_usage_seconds_total{job=\"cadvisor\", namespace=\"main\", container=\"$app\", image!=\"\"}[1m]))",
     "legendFormat": "container"
    },
    {
     "expr": "max by (container) (container_spec_cpu_quota{job=\"cadvisor\", namespace=\"main\", container=\"$app\", image!=\"\"}) / max by (container) (container_spec_cpu_period{job=\"cadvisor\", namespace=\"main\", container=\"$app\", image!=\"\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (container) (rate(container_cpu_cfs_throttled_periods_total{job=\"cadvisor\", namespace=\"main\", container=\"$app\", image!=\"\"}[1m]))\n/\nmax by (container) (rate(container_cpu_cfs_periods_total{job=\"cadvisor\", namespace=\"main\", container=\"$app\", image!=\"\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"$app\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"$app\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"$app\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{job=\"$app\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{job=\"$app\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open_files{job=\"$app\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{job=\"$app\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "persistence_counts" },
  {
   "title": "Memory Pool Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=~\"$app\", area=\"heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{job=\"$app\", area=\"heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{job=\"$app\", area=\"heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"$app\", area=\"nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{job=\"$app\", area=\"nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{job=\"$app\", area=\"nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{job=\"$app\"}[2m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{job=\"$app\"}[1m])/rate(jvm_gc_pause_seconds_count{job=\"$app\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{job=\"$app\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{job=\"$app\", area=\"nonheap\"}[2m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{job=\"$app\", area=\"nonheap\"}[2m])",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{job=\"$app\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{job=\"$app\"}[2m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "HTTP Edpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Total number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"$app\", uri!~\"/health/.*\", uri!=\"/metrics\"}[1m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Average inbound request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$app\", uri!~\"/health/.*\", uri!=\"/metrics\"}[4m]) / rate(http_server_requests_seconds_count{job=\"$app\", uri!~\"/health/.*\", uri!=\"/metrics\"}[4m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Maximum inbound request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"$app\", uri!~\"/health/.*\", uri!=\"/metrics\"}",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Sum of the duration of every request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$app\", uri!~\"/health/.*\", uri!=\"/metrics\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  }
 ]
}